# Shared config for all deploy scripts
REMOTE_IP="10.20.8.242"
REMOTE_USER="ec2-user"
REMOTE_DIR="/home/ec2-user/myrush-prod"
SSH_KEY="/home/fvm/Documents/Rush/myrush-prod-ssh.pem"  # Adjust this to your key location
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no"
